apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-nginx-deployment
  labels:
    app: app1-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1-nginx
  template:
    metadata:
      labels:
        app: app1-nginx
    spec:
      containers:
        - name: app1-nginx
          image: stacksimplify/kube-nginxapp1:1.0.0
          ports:
            - containerPort: 80
# To schedule pods on based on NodeSelectors
      nodeSelector:
        app: system-apps
---
apiVersion: v1
kind: Service
metadata:
  name: app1-nginx-clusterip-service
  labels:
    app: app1-nginx
spec:
  type: LoadBalancer
  selector:
    app: app1-nginx
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: windows-app1-deployment
  labels:
    app: windows-app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: windows-app1  
  template:
    metadata:
      name: windows-app1
      labels:
        app: windows-app1
    spec:
# To schedule pods on based on NodeSelectors      
      nodeSelector:
        #"beta.kubernetes.io/os": windows
        app: dotnet-apps
      containers:
      - name: windows-app1
        image: mcr.microsoft.com/dotnet/framework/samples:aspnetapp
        resources:
          limits:
            cpu: 1
            memory: 800M
          requests:
            cpu: .1
            memory: 300M
        ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: windows-app1-loadbalancer-service
spec:
  type: LoadBalancer
  selector:
    app: windows-app1  
  ports:
  - protocol: TCP
    port: 80
    
      

   